from fractions import Fraction

annotated_data_corrected = [('12 egg whites', [Fraction(12, 1), '', 'egg whites ']),
                            ('12 egg yolks', [Fraction(12, 1), '', 'egg yolks ']),
                            ('1 1/2 cups sugar', [Fraction(3, 2), 'cup', 'sugar ']),
                            ('3/4 cup rye whiskey', [Fraction(3, 4), 'cup', 'rye whiskey ']),
                            ('12 egg whites', [Fraction(12, 1), '', 'egg whites ']),
                            ('3/4 cup brandy', [Fraction(3, 4), 'cup', 'brandy ']),
                            ('1/2 cup rum', [Fraction(1, 2), 'cup', 'rum ']),
                            ('1 to 2 cups heavy cream, lightly whipped', [Fraction(2, 1), 'cup', 'heavy cream ']),
                            ('Garnish: ground nutmeg', [0, '', 'ground nutmeg ']),
                            ('18 fresh chestnuts', [Fraction(18, 1), '', 'fresh chestnuts ']),
                            ('2 1/2 pounds veal stew meat, cut into 2x1-inch pieces',
                             [Fraction(5, 2), 'pound', 'veal stew meat ']),
                            ('4 tablespoons olive oil', [Fraction(4, 1), 'tablespoon', 'olive oil ']),
                            ('1 1/2 cups chopped onion', [Fraction(3, 2), 'cup', 'onion ']),
                            ('1 1/2 tablespoons chopped garlic', [Fraction(3, 2), 'tablespoon', 'garlic']),
                            ('1 bay leaf', [Fraction(1, 1), '', 'bay leaf ']),
                            ('2 1/2 cups canned low-salt chicken broth',
                             [Fraction(5, 2), 'cup', 'canned low-salt chicken broth ']),
                            ('3/4 cup dry white wine', [Fraction(3, 4), 'cup', 'dry white wine ']),
                            ('6 medium carrots, peeled, cut into 1-inch pieces',
                             [Fraction(6, 1), '', 'medium carrots ']),
                            ('3 tablespoons chopped fresh sage', [Fraction(3, 1), 'tablespoon', 'fresh sage ']),
                            ('2 tablespoons unsalted butter, softened',
                             [Fraction(2, 1), 'tablespoon', 'unsalted butter ']),
                            (
                            '4 or 5 slices brioche, or good quality white bread (I like Pepperidge Farm), 1/4 inch thick, crusts removed',
                            [Fraction(5, 1), 'slices', 'brioche']),
                            ('3 extra-large eggs', [Fraction(3, 1), '', 'extra-large eggs ']),
                            ('2 extra-large egg yolks', [Fraction(2, 1), '', 'extra-large egg yolks ']),
                            ('1/4 cup brown sugar', [Fraction(1, 4), 'cup', 'brown sugar ']),
                            ('1 1/2 cups heavy cream', [Fraction(3, 2), 'cup', 'heavy cream ']),
                            ('1 1/4 cups whole milk', [Fraction(5, 4), 'cup', 'whole milk ']),
                            ('1 teaspoon pure vanilla extract', [Fraction(1, 1), 'teaspoon', 'vanilla extract ']),
                            ('1/2 teaspoon ground cinnamon', [Fraction(1, 2), 'teaspoon', 'ground cinnamon ']),
                            ('1/4 teaspoon freshly grated nutmeg', [Fraction(1, 4), 'teaspoon', 'nutmeg ']),
                            ('1/4 teaspoon kosher salt', [Fraction(1, 4), 'teaspoon', '']),
                            (
                            '3/4 cup chopped bittersweet chocolate', [Fraction(3, 4), 'cup', 'bittersweet chocolate ']),
                            ('1 tablespoon granulated sugar, for caramelizing the top',
                             [Fraction(1, 1), 'tablespoon', 'granulated sugar ']),
                            ('3/4 pound Stilton, crumbled (about 3 cups) and softened',
                             [Fraction(3, 4), 'pound', 'Stilton ']),
                            ('6 ounces cream cheese, softened', [Fraction(6, 1), 'ounce', 'cream cheese ']),
                            ('2 to 3 tablespoons drained green peppercorns packed in brine',
                             [Fraction(3, 1), 'tablespoon', 'green peppercorns ']),
                            ('1/4 cup medium-dry Sherry, or to taste', [Fraction(1, 4), 'cup', 'medium-dry Sherry ']),
                            ('2 cups (about 9 1/2 ounces) whole almonds, toasted',
                             [Fraction(1, 2), 'cups', 'whole almonds ']),
                            ('1 cup sugar', [Fraction(1, 1), 'cup', 'sugar ']),
                            ('1/4 teaspoon ground cinnamon', [Fraction(1, 4), 'teaspoon', 'ground cinnamon ']),
                            ('1/8 teaspoon salt', [Fraction(1, 8), 'teaspoon', '']),
                            ('1 large egg', [Fraction(1, 1), '', 'large egg ']),
                            ('2 large egg white', [Fraction(2, 1), '', 'large egg white']),
                            ('1/4 teaspoon almond extract', [Fraction(1, 4), 'teaspoon', 'almond extract ']),
                            ('3/4 cup finely chopped bittersweet (not unsweetened) or semisweet chocolate',
                             [Fraction(3, 4), 'cup', 'bittersweet or semisweet chocolate ']),
                            ('2 tablespoons butter', [Fraction(2, 1), 'tablespoon', 'butter ']),
                            ('2 tablespoons flour', [Fraction(2, 1), 'tablespoon', 'flour ']),
                            ('1 1/4 cups milk, heated', [Fraction(5, 4), 'cup', 'milk ']),
                            ('Salt', [0, '', '']),
                            ('Freshly ground pepper', [0, '', 'ground pepper ']),
                            ('1/2 teaspoon finely grated fresh lemon zest',
                             [Fraction(1, 2), 'teaspoon', 'fresh lemon zest ']),
                            ('1 1/2 tablespoons fresh lemon juice', [Fraction(3, 2), 'tablespoon', 'lemon juice ']),
                            ('1/3 cup extra-virgin olive oil', [Fraction(1, 3), 'cup', 'extra-virgin olive oil ']),
                            ('1/4 cup pitted Kalamata olives (1 1/4 oz), cut into slivers',
                             [Fraction(1, 4), 'cup', 'pitted Kalamata olives ']),
                            ('3 tablespoons finely chopped fresh oregano plus 6 large sprigs',
                             [Fraction(3, 1), 'tablespoon', 'fresh oregano ']),
                            ('1 (3 1/4- to 3 1/2-lb) cleaned whole Spanish mackerel or bluefish (with head and tail)',
                             [Fraction(1, 1), '', 'whole Spanish mackerel or bluefish ']),
                            ('2 tablespoons vegetable oil', [Fraction(2, 1), 'tablespoon', 'vegetable oil ']),
                            ('6 (1/4-inch-thick) lemon slices', [Fraction(6, 1), '', 'lemon slices ']),
                            ('Special equipment: a 22-inch grill; kitchen string',
                             [0, '', 'Special equipment 22-inch grill kitchen string ']),
                            ('2 garlic cloves, finely chopped', [Fraction(2, 1), 'clove', 'garlic ']),
                            ('2 teaspoons finely chopped peeled fresh ginger',
                             [Fraction(2, 1), 'teaspoon', ' fresh ginger ']),
                            ('1 tablespoon vegetable oil', [Fraction(1, 1), 'tablespoon', 'vegetable oil ']),
                            ('1 teaspoon mustard seeds', [Fraction(1, 1), 'teaspoon', 'mustard seeds ']),
                            ('3/4 cup dried apricots (6 oz), finely chopped',
                             [Fraction(3, 4), 'cup', 'dried apricots ']),
                            ('1/3 cup dried currants (1 1/2 oz)', [Fraction(1, 3), 'cup', 'dried currants ']),
                            ('3/4 cup water', [Fraction(3, 4), 'cup', '']),
                            ('1/3 cup red-wine vinegar', [Fraction(1, 3), 'cup', 'red-wine vinegar ']),
                            ('1/4 cup sugar', [Fraction(1, 4), 'cup', 'sugar ']),
                            ('3/4 teaspoon salt', [Fraction(3, 4), 'teaspoon', '']),
                            ('2 tablespoons (1/4 stick) butter', [Fraction(2, 1), 'tablespoon', 'butter ']),
                            ('1/4 cup olive oil', [Fraction(1, 4), 'cup', 'olive oil ']),
                            ('2 large garlic cloves, pressed', [Fraction(2, 1), 'clove', 'garlic ']),
                            ('4 French bread slices, cut into 3/4-inch cubes',
                             [Fraction(4, 1), 'slice', 'French bread ']),
                            ('1 recipe pate chou', [Fraction(1, 1), '', 'recipe pate chou ']),
                            ('About 1 cup pastry cream', [Fraction(1, 1), 'cup', 'pastry cream ']),
                            ('1/2 cup heavy cream', [Fraction(1, 2), 'cup', 'heavy cream ']),
                            ('1 recipe chocolate sauce', [Fraction(1, 1), '', 'recipe chocolate sauce ']),
                            ("Assorted candy decorations such as M&M;'s, Red Hots, licorice balls, and silver drapes",
                             [0, '', 'Assorted candy decorations ']),
                            ('Special equipment: Large pastry bag with 1/2-inch and 1/4-inch plain tips, '
                             'clear tape, 18-inch-tall Styrofoam cone (available at floral shops and '
                             'craft stores), parchment paper, cake-decorating turntable (optional), about '
                             '70 toothpicks, thimble, cloth leaves (available at floral shops and craft '
                             'stores)',
                             [Fraction(70, 1), '', 'Special equipment Large pastry bag cloth leaves ']),
                            ('2 1/2 cups all purpose flour', [Fraction(5, 2), 'cup', 'purpose flour ']),
                            ('1/4 cup unsweetened cocoa powder', [Fraction(1, 4), 'cup', 'unsweetened cocoa powder ']),
                            ('1/2 teaspoon baking powder', [Fraction(1, 2), 'teaspoon', 'baking powder ']),
                            ('1/2 teaspoon salt', [Fraction(1, 2), 'teaspoon', '']),
                            ('1/4 teaspoon baking soda', [Fraction(1, 4), 'teaspoon', 'baking soda ']),
                            ('1/2 teaspoon ground cinnamon (optional)',
                             [Fraction(1, 2), 'teaspoon', 'ground cinnamon ']),
                            ('3 ounces bittersweet chocolate, chopped',
                             [Fraction(3, 1), 'ounce', 'bittersweet chocolate ']),
                            ('1 cup (2 sticks) butter, room temperature',
                             [Fraction(1, 1), 'cup', 'butter room ']),
                            ('1 1/3 cups sugar', [Fraction(4, 3), 'cup', 'sugar ']),
                            ('1 large egg', [Fraction(1, 1), '', 'large egg ']),
                            ('1/2 teaspoon vanilla extract',
                             [Fraction(1, 2), 'teaspoon', 'vanilla extract ']),
                            ('Sprinkles or other sugar decorations (optional)', [0, '', 'Sprinkles ']),
                            ('Royal Icing (optional)', [0, '', 'Royal Icing ']),
                            ('2 tablespoons brewed coffee', [Fraction(2, 1), 'tablespoon', 'coffee ']),
                            ('1 ounce semisweet chocolate, chopped',
                             [Fraction(1, 1), 'ounce', 'semisweet chocolate ']),
                            ('1/4 teaspoon vanilla', [Fraction(1, 4), 'teaspoon', 'vanilla ']),
                            ('1/8 teaspoon cornstarch', [Fraction(1, 8), 'teaspoon', 'cornstarch ']),
                            ('Pinch cinnamon', [0, '', 'cinnamon ']),
                            ('1 cup all purpose flour', [Fraction(1, 1), 'cup', 'all purpose flour']),
                            ('1/2 teaspoon ground cinnamon',
                             [Fraction(1, 2), 'teaspoon', 'ground cinnamon ']),
                            ('1/2 teaspoon baking soda', [Fraction(1, 2), 'teaspoon', 'baking soda ']),
                            ('1/4 teaspoon salt', [Fraction(1, 4), 'teaspoon', ''])]
