combined_data = [('12 egg whites', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('12 egg yolks', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('1 1/2 cups sugar', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('3/4 cup rye whiskey', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('12 egg whites', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('3/4 cup brandy', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/2 cup rum', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 to 2 cups heavy cream, lightly whipped',
                  {'entities': [(0, 11, 'QUANTITY')]}),
                 ('Garnish: ground nutmeg', {'entities': [(0, 7, 'NORP')]}),
                 ('18 fresh chestnuts', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('2 1/2 pounds veal stew meat, cut into 2x1-inch pieces',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('4 tablespoons olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('1 1/2 cups chopped onion', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 1/2 tablespoons chopped garlic', {'entities': [(0, 17, 'QUANTITY')]}),
                 ('1 bay leaf', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 1/2 cups canned low-salt chicken broth',
                  {'entities': [(0, 10, 'QUANTITY')]}),
                 ('3/4 cup dry white wine', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('6 medium carrots, peeled, cut into 1-inch pieces',
                  {'entities': [(0, 1, 'CARDINAL'), (35, 48, 'QUANTITY')]}),
                 ('3 tablespoons chopped fresh sage', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('2 tablespoons unsalted butter, softened',
                  {'entities': [(0, 13, 'QUANTITY')]}),
                 ('4 or 5 slices brioche, or good quality white bread (I like Pepperidge '
                  'Farm), 1/4 inch thick, crusts removed',
                  {'entities': [(0, 13, 'QUANTITY'), (77, 85, 'QUANTITY'), (59, 74, 'ORG')]}),
                 ('3 extra-large eggs', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 extra-large egg yolks', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('1/4 cup brown sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 1/2 cups heavy cream', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 1/4 cups whole milk', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 teaspoon pure vanilla extract', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1/2 teaspoon ground cinnamon', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon freshly grated nutmeg', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon kosher salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3/4 cup chopped bittersweet chocolate', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 tablespoon granulated sugar, for caramelizing the top',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3/4 pound Stilton, crumbled (about 3 cups) and softened',
                  {'entities': [(0, 9, 'QUANTITY'), (35, 41, 'QUANTITY')]}),
                 ('6 ounces cream cheese, softened', {'entities': [(0, 8, 'QUANTITY')]}),
                 ('2 to 3 tablespoons drained green peppercorns packed in brine',
                  {'entities': [(0, 18, 'QUANTITY')]}),
                 ('1/4 cup medium-dry Sherry, or to taste',
                  {'entities': [(0, 7, 'QUANTITY'), (19, 25, 'PERSON')]}),
                 ('2 cups (about 9 1/2 ounces) whole almonds, toasted',
                  {'entities': [(0, 6, 'QUANTITY'), (14, 26, 'QUANTITY')]}),
                 ('1 cup sugar', {'entities': [(0, 5, 'QUANTITY')]}),
                 ('1/4 teaspoon ground cinnamon', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/8 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1 large egg', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 large egg white', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('1/4 teaspoon almond extract', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3/4 cup finely chopped bittersweet (not unsweetened) or semisweet chocolate',
                  {'entities': [(0, 7, 'QUANTITY')]}),
                 ('2 tablespoons butter', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('2 tablespoons flour', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('1 1/4 cups milk, heated', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('Salt', {'entities': []}),
                 ('Freshly ground pepper', {'entities': []}),
                 ('1/2 teaspoon finely grated fresh lemon zest',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1 1/2 tablespoons fresh lemon juice', {'entities': [(0, 17, 'QUANTITY')]}),
                 ('1/3 cup extra-virgin olive oil', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/4 cup pitted Kalamata olives (1 1/4 oz), cut into slivers',
                  {'entities': [(0, 7, 'QUANTITY'), (32, 40, 'QUANTITY'), (15, 23, 'PERSON')]}),
                 ('3 tablespoons finely chopped fresh oregano plus 6 large sprigs',
                  {'entities': [(0, 13, 'QUANTITY'), (48, 49, 'CARDINAL')]}),
                 ('1 (3 1/4- to 3 1/2-lb) cleaned whole Spanish mackerel or bluefish (with '
                  'head and tail)',
                  {'entities': [(0, 22, 'QUANTITY'), (37, 44, 'NORP')]}),
                 ('2 tablespoons vegetable oil', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('6 (1/4-inch-thick) lemon slices', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('Special equipment: a 22-inch grill; kitchen string', {'entities': []}),
                 ('2 garlic cloves, finely chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 teaspoons finely chopped peeled fresh ginger',
                  {'entities': [(0, 11, 'QUANTITY')]}),
                 ('1 tablespoon vegetable oil', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1 teaspoon mustard seeds', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('3/4 cup dried apricots (6 oz), finely chopped',
                  {'entities': [(0, 7, 'QUANTITY'), (24, 28, 'QUANTITY')]}),
                 ('1/3 cup dried currants (1 1/2 oz)',
                  {'entities': [(0, 7, 'QUANTITY'), (24, 32, 'QUANTITY')]}),
                 ('3/4 cup water', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/3 cup red-wine vinegar', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/4 cup sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('3/4 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('2 tablespoons (1/4 stick) butter',
                  {'entities': [(0, 13, 'QUANTITY'), (15, 24, 'QUANTITY')]}),
                 ('1/4 cup olive oil', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('2 large garlic cloves, pressed', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('4 French bread slices, cut into 3/4-inch cubes',
                  {'entities': [(0, 8, 'QUANTITY'), (32, 46, 'QUANTITY'), (2, 8, 'NORP')]}),
                 ('1 recipe pate chou', {'entities': [(0, 1, 'CARDINAL'), (14, 18, 'GPE')]}),
                 ('About 1 cup pastry cream', {'entities': [(0, 11, 'QUANTITY')]}),
                 ('1/2 cup heavy cream', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 recipe chocolate sauce', {'entities': [(0, 1, 'CARDINAL')]}),
                 ("Assorted candy decorations such as M&M;'s, Red Hots, licorice balls, and "
                  'silver drapes',
                  {'entities': [(35, 38, 'ORG'), (43, 51, 'FAC')]}),
                 ('Special equipment: Large pastry bag with 1/2-inch and 1/4-inch plain tips, '
                  'clear tape, 18-inch-tall Styrofoam cone (available at floral shops and '
                  'craft stores), parchment paper, cake-decorating turntable (optional), about '
                  '70 toothpicks, thimble, cloth leaves (available at floral shops and craft '
                  'stores)',
                  {'entities': [(41, 68, 'QUANTITY'),
                                (87, 95, 'QUANTITY'),
                                (222, 235, 'QUANTITY'),
                                (100, 109, 'ORG')]}),
                 ('2 1/2 cups all purpose flour', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1/4 cup unsweetened cocoa powder', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/2 teaspoon baking powder', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/2 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon baking soda', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/2 teaspoon ground cinnamon (optional)',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3 ounces bittersweet chocolate, chopped',
                  {'entities': [(0, 8, 'QUANTITY')]}),
                 ('1 cup (2 sticks) butter, room temperature',
                  {'entities': [(0, 5, 'QUANTITY')]}),
                 ('1 1/3 cups sugar', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 large egg', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('1/2 teaspoon vanilla extract', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('Sprinkles or other sugar decorations (optional)', {'entities': []}),
                 ('Royal Icing (optional)', {'entities': [(0, 11, 'PERSON')]}),
                 ('2 tablespoons brewed coffee', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('1 ounce semisweet chocolate, chopped', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/4 teaspoon vanilla', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/8 teaspoon cornstarch', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('Pinch cinnamon', {'entities': []}),
                 ('1 cup all purpose flour', {'entities': [(0, 5, 'QUANTITY')]}),
                 ('1/2 teaspoon ground cinnamon', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/2 teaspoon baking soda', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]})]

new_annotated_data = [('1 cup flour, sifted', {'entities': [(6, 11, 'INGREDIENT')]}),
 ('1 teaspoons sea salt', {'entities': [(12, 20, 'INGREDIENT')]}),
 ('1 egg', {'entities': [(2, 5, 'INGREDIENT')]}),
 ('1/2 cup milk', {'entities': [(8, 12, 'INGREDIENT')]}),
 ('1 rounded tablespoon baking powder', {'entities': [(21, 34, 'INGREDIENT')]}),
 ('2 tablespoons olive oil', {'entities': [(14, 23, 'INGREDIENT')]}),
 ('3 cups lightly toasted sesame seeds',
  {'entities': [(23, 35, 'INGREDIENT')]}),
 ('1 (8 oz) package ground beef', {'entities': [(17, 28, 'INGREDIENT')]})]