combined_data = [('12 egg whites', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('12 egg yolks', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('1 1/2 cups sugar', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('3/4 cup rye whiskey', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('12 egg whites', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('3/4 cup brandy', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/2 cup rum', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 to 2 cups heavy cream, lightly whipped',
                  {'entities': [(0, 11, 'QUANTITY')]}),
                 ('Garnish: ground nutmeg', {'entities': [(0, 7, 'NORP')]}),
                 ('18 fresh chestnuts', {'entities': [(0, 2, 'CARDINAL')]}),
                 ('2 1/2 pounds veal stew meat, cut into 2x1-inch pieces',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('4 tablespoons olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('1 1/2 cups chopped onion', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 1/2 tablespoons chopped garlic', {'entities': [(0, 17, 'QUANTITY')]}),
                 ('1 bay leaf', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 1/2 cups canned low-salt chicken broth',
                  {'entities': [(0, 10, 'QUANTITY')]}),
                 ('3/4 cup dry white wine', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('6 medium carrots, peeled, cut into 1-inch pieces',
                  {'entities': [(0, 1, 'CARDINAL'), (35, 48, 'QUANTITY')]}),
                 ('3 tablespoons chopped fresh sage', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('2 tablespoons unsalted butter, softened',
                  {'entities': [(0, 13, 'QUANTITY')]}),
                 ('4 or 5 slices brioche, or good quality white bread (I like Pepperidge '
                  'Farm), 1/4 inch thick, crusts removed',
                  {'entities': [(0, 13, 'QUANTITY'), (77, 85, 'QUANTITY'), (59, 74, 'ORG')]}),
                 ('3 extra-large eggs', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 extra-large egg yolks', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('1/4 cup brown sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 1/2 cups heavy cream', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 1/4 cups whole milk', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 teaspoon pure vanilla extract', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1/2 teaspoon ground cinnamon', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon freshly grated nutmeg', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon kosher salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3/4 cup chopped bittersweet chocolate', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 tablespoon granulated sugar, for caramelizing the top',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3/4 pound Stilton, crumbled (about 3 cups) and softened',
                  {'entities': [(0, 9, 'QUANTITY'), (35, 41, 'QUANTITY')]}),
                 ('6 ounces cream cheese, softened', {'entities': [(0, 8, 'QUANTITY')]}),
                 ('2 to 3 tablespoons drained green peppercorns packed in brine',
                  {'entities': [(0, 18, 'QUANTITY')]}),
                 ('1/4 cup medium-dry Sherry, or to taste',
                  {'entities': [(0, 7, 'QUANTITY'), (19, 25, 'PERSON')]}),
                 ('2 cups (about 9 1/2 ounces) whole almonds, toasted',
                  {'entities': [(0, 6, 'QUANTITY'), (14, 26, 'QUANTITY')]}),
                 ('1 cup sugar', {'entities': [(0, 5, 'QUANTITY')]}),
                 ('1/4 teaspoon ground cinnamon', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/8 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1 large egg', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 large egg white', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('1/4 teaspoon almond extract', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3/4 cup finely chopped bittersweet (not unsweetened) or semisweet chocolate',
                  {'entities': [(0, 7, 'QUANTITY')]}),
                 ('2 tablespoons butter', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('2 tablespoons flour', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('1 1/4 cups milk, heated', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('Salt', {'entities': []}),
                 ('Freshly ground pepper', {'entities': []}),
                 ('1/2 teaspoon finely grated fresh lemon zest',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1 1/2 tablespoons fresh lemon juice', {'entities': [(0, 17, 'QUANTITY')]}),
                 ('1/3 cup extra-virgin olive oil', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/4 cup pitted Kalamata olives (1 1/4 oz), cut into slivers',
                  {'entities': [(0, 7, 'QUANTITY'), (32, 40, 'QUANTITY'), (15, 23, 'PERSON')]}),
                 ('3 tablespoons finely chopped fresh oregano plus 6 large sprigs',
                  {'entities': [(0, 13, 'QUANTITY'), (48, 49, 'CARDINAL')]}),
                 ('1 (3 1/4- to 3 1/2-lb) cleaned whole Spanish mackerel or bluefish (with '
                  'head and tail)',
                  {'entities': [(0, 22, 'QUANTITY'), (37, 44, 'NORP')]}),
                 ('2 tablespoons vegetable oil', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('6 (1/4-inch-thick) lemon slices', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('Special equipment: a 22-inch grill; kitchen string', {'entities': []}),
                 ('2 garlic cloves, finely chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('2 teaspoons finely chopped peeled fresh ginger',
                  {'entities': [(0, 11, 'QUANTITY')]}),
                 ('1 tablespoon vegetable oil', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1 teaspoon mustard seeds', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('3/4 cup dried apricots (6 oz), finely chopped',
                  {'entities': [(0, 7, 'QUANTITY'), (24, 28, 'QUANTITY')]}),
                 ('1/3 cup dried currants (1 1/2 oz)',
                  {'entities': [(0, 7, 'QUANTITY'), (24, 32, 'QUANTITY')]}),
                 ('3/4 cup water', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/3 cup red-wine vinegar', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/4 cup sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('3/4 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('2 tablespoons (1/4 stick) butter',
                  {'entities': [(0, 13, 'QUANTITY'), (15, 24, 'QUANTITY')]}),
                 ('1/4 cup olive oil', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('2 large garlic cloves, pressed', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('4 French bread slices, cut into 3/4-inch cubes',
                  {'entities': [(0, 8, 'QUANTITY'), (32, 46, 'QUANTITY'), (2, 8, 'NORP')]}),
                 ('1 recipe pate chou', {'entities': [(0, 1, 'CARDINAL'), (14, 18, 'GPE')]}),
                 ('About 1 cup pastry cream', {'entities': [(0, 11, 'QUANTITY')]}),
                 ('1/2 cup heavy cream', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1 recipe chocolate sauce', {'entities': [(0, 1, 'CARDINAL')]}),
                 ("Assorted candy decorations such as M&M;'s, Red Hots, licorice balls, and "
                  'silver drapes',
                  {'entities': [(35, 38, 'ORG'), (43, 51, 'FAC')]}),
                 ('Special equipment: Large pastry bag with 1/2-inch and 1/4-inch plain tips, '
                  'clear tape, 18-inch-tall Styrofoam cone (available at floral shops and '
                  'craft stores), parchment paper, cake-decorating turntable (optional), about '
                  '70 toothpicks, thimble, cloth leaves (available at floral shops and craft '
                  'stores)',
                  {'entities': [(41, 68, 'QUANTITY'),
                                (87, 95, 'QUANTITY'),
                                (222, 235, 'QUANTITY'),
                                (100, 109, 'ORG')]}),
                 ('2 1/2 cups all purpose flour', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1/4 cup unsweetened cocoa powder', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/2 teaspoon baking powder', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/2 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon baking soda', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/2 teaspoon ground cinnamon (optional)',
                  {'entities': [(0, 12, 'QUANTITY')]}),
                 ('3 ounces bittersweet chocolate, chopped',
                  {'entities': [(0, 8, 'QUANTITY')]}),
                 ('1 cup (2 sticks) butter, room temperature',
                  {'entities': [(0, 5, 'QUANTITY')]}),
                 ('1 1/3 cups sugar', {'entities': [(0, 10, 'QUANTITY')]}),
                 ('1 large egg', {'entities': [(0, 1, 'CARDINAL')]}),
                 ('1/2 teaspoon vanilla extract', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('Sprinkles or other sugar decorations (optional)', {'entities': []}),
                 ('Royal Icing (optional)', {'entities': [(0, 11, 'PERSON')]}),
                 ('2 tablespoons brewed coffee', {'entities': [(0, 13, 'QUANTITY')]}),
                 ('1 ounce semisweet chocolate, chopped', {'entities': [(0, 7, 'QUANTITY')]}),
                 ('1/4 teaspoon vanilla', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/8 teaspoon cornstarch', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('Pinch cinnamon', {'entities': []}),
                 ('1 cup all purpose flour', {'entities': [(0, 5, 'QUANTITY')]}),
                 ('1/2 teaspoon ground cinnamon', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/2 teaspoon baking soda', {'entities': [(0, 12, 'QUANTITY')]}),
                 ('1/4 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]})]

new_annotated_data = [('12 egg whites', {'entities': [(3, 13, 'INGREDIENT'), (0, 2, 'CARDINAL')]}),
                      ('12 egg yolks', {'entities': [(3, 12, 'INGREDIENT'), (0, 2, 'CARDINAL')]}),
                      ('1 1/2 cups sugar',
                       {'entities': [(11, 16, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('3/4 cup rye whiskey',
                       {'entities': [(8, 19, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('12 egg whites', {'entities': [(3, 13, 'INGREDIENT'), (0, 2, 'CARDINAL')]}),
                      ('3/4 cup brandy', {'entities': [(8, 14, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1/2 cup rum', {'entities': [(8, 11, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1 to 2 cups heavy cream, lightly whipped',
                       {'entities': [(12, 23, 'INGREDIENT'), (0, 11, 'QUANTITY')]}),
                      ('Garnish: ground nutmeg',
                       {'entities': [(16, 22, 'INGREDIENT')]}),
                      ('18 fresh chestnuts',
                       {'entities': [(9, 18, 'INGREDIENT'), (0, 2, 'CARDINAL')]}),
                      ('2 1/2 pounds veal stew meat, cut into 2x1-inch pieces',
                       {'entities': [(13, 27, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('4 tablespoons olive oil',
                       {'entities': [(14, 23, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('1 1/2 cups chopped onion',
                       {'entities': [(19, 24, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('1 1/2 tablespoons chopped garlic',
                       {'entities': [(26, 32, 'INGREDIENT'), (0, 17, 'QUANTITY')]}),
                      ('1 bay leaf', {'entities': [(2, 10, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('2 1/2 cups canned low-salt chicken broth',
                       {'entities': [(18, 40, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('3/4 cup dry white wine',
                       {'entities': [(8, 22, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('6 medium carrots, peeled, cut into 1-inch pieces',
                       {'entities': [(9, 16, 'INGREDIENT'),
                                     (0, 1, 'CARDINAL'),
                                     (35, 48, 'QUANTITY')]}),
                      ('3 tablespoons chopped fresh sage',
                       {'entities': [(28, 32, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('2 tablespoons unsalted butter, softened',
                       {'entities': [(14, 29, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('4 or 5 slices brioche, or good quality white bread (I like Pepperidge '
                       'Farm), 1/4 inch thick, crusts removed',
                       {'entities': [(14, 21, 'INGREDIENT'),
                                     (39, 50, 'INGREDIENT'),
                                     (0, 13, 'QUANTITY'),
                                     (77, 85, 'QUANTITY'),
                                     (59, 74, 'ORG')]}),
                      ('3 extra-large eggs',
                       {'entities': [(14, 18, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('2 extra-large egg yolks',
                       {'entities': [(14, 23, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('1/4 cup brown sugar',
                       {'entities': [(8, 19, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1 1/2 cups heavy cream',
                       {'entities': [(11, 22, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('1 1/4 cups whole milk',
                       {'entities': [(11, 21, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('1 teaspoon pure vanilla extract',
                       {'entities': [(16, 31, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('1/2 teaspoon ground cinnamon',
                       {'entities': [(20, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/4 teaspoon freshly grated nutmeg',
                       {'entities': [(28, 34, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/4 teaspoon kosher salt',
                       {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('3/4 cup chopped bittersweet chocolate',
                       {'entities': [(16, 37, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1 tablespoon granulated sugar, for caramelizing the top',
                       {'entities': [(24, 29, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('3/4 pound Stilton, crumbled (about 3 cups) and softened',
                       {'entities': [(10, 17, 'INGREDIENT'),
                                     (0, 9, 'QUANTITY'),
                                     (35, 41, 'QUANTITY')]}),
                      ('6 ounces cream cheese, softened',
                       {'entities': [(9, 21, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                      ('2 to 3 tablespoons drained green peppercorns packed in brine',
                       {'entities': [(27, 44, 'INGREDIENT'), (0, 18, 'QUANTITY')]}),
                      ('1/4 cup medium-dry Sherry, or to taste',
                       {'entities': [(19, 25, 'INGREDIENT'),
                                     (0, 7, 'QUANTITY')]}),
                      ('2 cups (about 9 1/2 ounces) whole almonds, toasted',
                       {'entities': [(34, 41, 'INGREDIENT'),
                                     (0, 6, 'QUANTITY'),
                                     (14, 26, 'QUANTITY')]}),
                      ('1 cup sugar', {'entities': [(6, 11, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                      ('1/4 teaspoon ground cinnamon',
                       {'entities': [(20, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/8 teaspoon salt',
                       {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1 large egg', {'entities': [(8, 11, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('2 large egg white',
                       {'entities': [(8, 17, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('1/4 teaspoon almond extract',
                       {'entities': [(13, 27, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('3/4 cup finely chopped bittersweet (not unsweetened) or semisweet chocolate',
                       {'entities': [(56, 75, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('2 tablespoons butter',
                       {'entities': [(14, 20, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('2 tablespoons flour',
                       {'entities': [(14, 19, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('1 1/4 cups milk, heated',
                       {'entities': [(11, 15, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('Salt', {'entities': [(0, 4, 'INGREDIENT')]}),
                      ('Freshly ground pepper', {'entities': [(15, 21, 'INGREDIENT')]}),
                      ('1/2 teaspoon finely grated fresh lemon zest',
                       {'entities': [(33, 43, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1 1/2 tablespoons fresh lemon juice',
                       {'entities': [(24, 35, 'INGREDIENT'), (0, 17, 'QUANTITY')]}),
                      ('1/3 cup extra-virgin olive oil',
                       {'entities': [(21, 30, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1/4 cup pitted Kalamata olives (1 1/4 oz), cut into slivers',
                       {'entities': [(15, 30, 'INGREDIENT'),
                                     (0, 7, 'QUANTITY'),
                                     (32, 40, 'QUANTITY')]}),
                      ('3 tablespoons finely chopped fresh oregano plus 6 large sprigs',
                       {'entities': [(29, 42, 'INGREDIENT'),
                                     (0, 13, 'QUANTITY'),
                                     (48, 49, 'CARDINAL')]}),
                      ('1 (3 1/4- to 3 1/2-lb) cleaned whole Spanish mackerel or bluefish (with '
                       'head and tail)',
                       {'entities': [(37, 53, 'INGREDIENT'),
                                     (57, 65, 'INGREDIENT'),
                                     (0, 22, 'QUANTITY')]}),
                      ('2 tablespoons vegetable oil',
                       {'entities': [(14, 27, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('6 (1/4-inch-thick) lemon slices',
                       {'entities': [(19, 31, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('2 garlic cloves, finely chopped',
                       {'entities': [(2, 8, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('2 teaspoons finely chopped peeled fresh ginger',
                       {'entities': [(34, 46, 'INGREDIENT'), (0, 11, 'QUANTITY')]}),
                      ('1 tablespoon vegetable oil',
                       {'entities': [(13, 26, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1 teaspoon mustard seeds',
                       {'entities': [(11, 24, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('3/4 cup dried apricots (6 oz), finely chopped',
                       {'entities': [(8, 22, 'INGREDIENT'),
                                     (0, 7, 'QUANTITY'),
                                     (24, 28, 'QUANTITY')]}),
                      ('1/3 cup dried currants (1 1/2 oz)',
                       {'entities': [(8, 22, 'INGREDIENT'),
                                     (0, 7, 'QUANTITY'),
                                     (24, 32, 'QUANTITY')]}),
                      ('3/4 cup water', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1/3 cup red-wine vinegar',
                       {'entities': [(8, 24, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1/4 cup sugar', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('3/4 teaspoon salt',
                       {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('2 tablespoons (1/4 stick) butter',
                       {'entities': [(26, 32, 'INGREDIENT'),
                                     (0, 13, 'QUANTITY'),
                                     (15, 24, 'QUANTITY')]}),
                      ('1/4 cup olive oil',
                       {'entities': [(8, 17, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('2 large garlic cloves, pressed',
                       {'entities': [(8, 14, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('4 French bread slices, cut into 3/4-inch cubes',
                       {'entities': [(2, 14, 'INGREDIENT'),
                                     (0, 1, 'CARDINAL'),
                                     (32, 46, 'QUANTITY')]}),
                      ('1 recipe pate chou',
                       {'entities': [(9, 18, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('About 1 cup pastry cream',
                       {'entities': [(12, 24, 'INGREDIENT'), (0, 11, 'QUANTITY')]}),
                      ('1/2 cup heavy cream',
                       {'entities': [(8, 19, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ("Assorted candy decorations such as M&M's, Red Hots, licorice balls, and "
                       'silver drapes',
                       {'entities': [(35, 40, 'INGREDIENT'),
                                     (43, 51, 'INGREDIENT'),
                                     (53, 67, 'INGREDIENT'),
                                     (73, 86, 'INGREDIENT')]}),
                      ('2 1/2 cups all purpose flour',
                       {'entities': [(11, 28, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('1/4 cup unsweetened cocoa powder',
                       {'entities': [(8, 32, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1/2 teaspoon baking powder',
                       {'entities': [(13, 26, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/2 teaspoon salt',
                       {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/4 teaspoon baking soda',
                       {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/2 teaspoon ground cinnamon (optional)',
                       {'entities': [(20, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('3 ounces bittersweet chocolate, chopped',
                       {'entities': [(9, 30, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                      ('1 cup (2 sticks) butter, room temperature',
                       {'entities': [(17, 23, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                      ('1 1/3 cups sugar',
                       {'entities': [(11, 16, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                      ('1 large egg', {'entities': [(8, 11, 'INGREDIENT'), (0, 1, 'CARDINAL')]}),
                      ('1/2 teaspoon vanilla extract',
                       {'entities': [(13, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('Sprinkles or other sugar decorations (optional)',
                       {'entities': [(0, 9, 'INGREDIENT')]}),
                      ('Royal Icing (optional)',
                       {'entities': [(0, 11, 'INGREDIENT')]}),
                      ('2 tablespoons brewed coffee',
                       {'entities': [(14, 27, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                      ('1 ounce semisweet chocolate, chopped',
                       {'entities': [(8, 27, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                      ('1/4 teaspoon vanilla',
                       {'entities': [(13, 20, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/8 teaspoon cornstarch',
                       {'entities': [(13, 23, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('Pinch cinnamon', {'entities': [(6, 14, 'INGREDIENT')]}),
                      ('1 cup all purpose flour',
                       {'entities': [(6, 23, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                      ('1/2 teaspoon ground cinnamon',
                       {'entities': [(20, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/2 teaspoon baking soda',
                       {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                      ('1/4 teaspoon salt',
                       {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]})]
annotated_for_testing = [('1 pound dried white beans such as cannellini (2 1/2 cups), picked over and rinsed',
                          {'entities': [(0, 7, 'QUANTITY'), (46, 56, 'QUANTITY')]}),
                         ('4 Confit Duck Legs at room temperature', {'entities': []}),
                         ('3 tablespoons extra-virgin olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                         ('2 medium onions, finely chopped', {'entities': []}),
                         ('2 large carrots, finely chopped', {'entities': []}),
                         ('2 celery ribs, finely chopped', {'entities': []}),
                         ('4 large garlic cloves, finely chopped', {'entities': []}),
                         ('2 Turkish bay leaves or 1 California', {'entities': []}),
                         ('2 large thyme sprigs', {'entities': []}),
                         ('2 whole cloves', {'entities': []}),
                         ('5 cups reduced-sodium chicken broth', {'entities': [(0, 6, 'QUANTITY')]}),
                         ('8 cups water', {'entities': [(0, 6, 'QUANTITY')]}),
                         ('1 (15-ounce) can diced tomatoes, drained', {'entities': [(0, 16, 'QUANTITY')]}),
                         ('1/3 cup Armagnac or Cognac', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1/2 cup chopped flat-leaf parsley', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1 cup fresh bread crumbs (about 2 slices)',
                          {'entities': [(0, 5, 'QUANTITY')]}),
                         ('2 tablespoons olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                         ('2 tablespoons drained bottled horseradish, or to taste',
                          {'entities': [(0, 13, 'QUANTITY')]}),
                         ('a 1-pound piece boneless pork loin', {'entities': [(2, 9, 'QUANTITY')]}),
                         ('1 1/2 tablespoons Dijon mustard', {'entities': [(0, 17, 'QUANTITY')]}),
                         ('Accompaniment if desired:', {'entities': []}),
                         ('2 tablespoons vegetable oil', {'entities': [(0, 13, 'QUANTITY')]}),
                         ('3/4 pound red cabbage, sliced thin (about 6 cups)',
                          {'entities': [(0, 9, 'QUANTITY')]}),
                         ('1 medium red onion, sliced thin', {'entities': []}),
                         ('1/4 cup water', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1/2 cup balsamic vinegar', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1 tablespoon sugar', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('2 cups all-purpose flour', {'entities': [(0, 6, 'QUANTITY')]}),
                         ('3/4 cup sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1 1/2 teaspoons baking powder', {'entities': [(0, 15, 'QUANTITY')]}),
                         ('1/2 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1/2 stick (1/4 cup) cold unsalted butter, cut into small pieces',
                          {'entities': [(11, 18, 'QUANTITY')]}),
                         ('1 whole large egg, lightly beaten', {'entities': []}),
                         ('1/3 cup whole milk', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1/2 teaspoon vanilla extract', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1/4 teaspoon almond extract', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1 cup whole almonds with skins (5 1/2 oz), toasted and cooled',
                          {'entities': [(0, 5, 'QUANTITY')]}),
                         ('1 cup dried apricots (6 oz), quartered', {'entities': [(0, 5, 'QUANTITY')]}),
                         ('1 large egg yolk beaten with 1 tablespoon water for egg wash',
                          {'entities': []}),
                         ('Special equipment: parchment paper', {'entities': []}),
                         ('1-1/2 teaspoons extra-virgin olive oil or garlic oil',
                          {'entities': [(0, 15, 'QUANTITY')]}),
                         ('1 teaspoon minced garlic', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1/4 cup fine dried bread crumbs', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('Pinch gray salt', {'entities': []}),
                         ('Freshly ground pepper', {'entities': []}),
                         ('1 tablespoon finely chopped fresh parsley',
                          {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1 teaspoon freshly grated lemon zest', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 tablespoon freshly grated Parmesan cheese',
                          {'entities': [(0, 12, 'QUANTITY')]}),
                         ('Unsalted butter for baking dish', {'entities': []}),
                         ('1 large bunch asparagus, about 1 pound, trimmed to even lengths and cooked '
                          'for 4 minutes in boiling, salted water',
                          {'entities': [(31, 38, 'QUANTITY')]}),
                         ('2 tablespoons extra-virgin olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                         ('Gray salt and freshly ground pepper', {'entities': []}),
                         ('8 thin slices prosciutto', {'entities': []}),
                         ('4 pounds McIntosh apples, peeled, cored, cut into 1-inch chunks',
                          {'entities': [(0, 8, 'QUANTITY')]}),
                         ('1 1/2 cups apple cider', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1/2 cup (packed) golden brown sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1 tablespoon lemon juice', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('2 tablespoons minced crystallized ginger',
                          {'entities': [(0, 13, 'QUANTITY')]}),
                         ('1 cup firmly packed dried figs (as soft as possible)',
                          {'entities': [(0, 5, 'QUANTITY')]}),
                         ('1 cup firmly packed pitted dates', {'entities': [(0, 5, 'QUANTITY')]}),
                         ('1/3 cup water', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1/2 cup plus 2 tablespoons granulated refined sugar',
                          {'entities': [(0, 7, 'QUANTITY'), (13, 26, 'QUANTITY')]}),
                         ('1 3/4 cups all-purpose flour', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 tablespoon ground anise seeds', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1/4 teaspoon baking powder', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1/4 teaspoon baking soda', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1/4 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1 stick (1/2 cup) unsalted butter, softened',
                          {'entities': [(9, 16, 'QUANTITY')]}),
                         ('4 ounces cream cheese', {'entities': [(0, 8, 'QUANTITY')]}),
                         ('1 teaspoon vanilla extract', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 large egg yolk', {'entities': []}),
                         ('1/4 cup granulated raw sugar (turbinado or Demerara)',
                          {'entities': [(0, 7, 'QUANTITY')]}),
                         ('4 pounds zucchini, peeled, quartered lengthwise, cored, and chopped',
                          {'entities': [(0, 8, 'QUANTITY')]}),
                         ('2 medium onions, chopped', {'entities': []}),
                         ('1 medium red bell pepper, chopped', {'entities': []}),
                         ('2 tablespoons salt', {'entities': [(0, 13, 'QUANTITY')]}),
                         ('1 1/2 cups sugar', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 cup water', {'entities': [(0, 5, 'QUANTITY')]}),
                         ('1 cup distilled white vinegar', {'entities': [(0, 5, 'QUANTITY')]}),
                         ('1 teaspoon celery seeds', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 teaspoon freshly grated nutmeg', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 teaspoon turmeric if desired', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1/2 teaspoon freshly ground black pepper, or to taste',
                          {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1/2 cup kosher salt', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('1/2 cup sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                         ('12 black peppercorns', {'entities': []}),
                         ('6 garlic coves, roughly chopped', {'entities': []}),
                         ('6 fresh thyme sprigs', {'entities': []}),
                         ('2 bay leaves', {'entities': []}),
                         ('1 small yellow onion, peeled and sliced into rings', {'entities': []}),
                         ('4 cups ice cubes', {'entities': [(0, 6, 'QUANTITY')]}),
                         ('One 3-pound boneless pork loin roast with a nice fat cap layer on top',
                          {'entities': [(4, 11, 'QUANTITY')]}),
                         ('1 large (about 4-ounce) Andouille sausage link',
                          {'entities': [(15, 22, 'QUANTITY')]}),
                         ('Kosher salt and freshly ground black pepper', {'entities': []}),
                         ('1 tablespoon granulated garlic', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1 tablespoon paprika', {'entities': [(0, 12, 'QUANTITY')]}),
                         ('1 teaspoon ground cumin', {'entities': [(0, 10, 'QUANTITY')]}),
                         ('1 to 2 tablespoons canola oil', {'entities': [(5, 18, 'QUANTITY')]}),
                         ("Creole mustard (e.g., Zatarain's)", {'entities': []}),
                         ('Grill with lid, large freezer bag, honing steel, instant-read meat '
                          'thermometer.',
                          {'entities': []})]

annotated_for_testing_with_CARDINAL = [('1 pound dried white beans such as cannellini (2 1/2 cups), picked over and '
                                        'rinsed',
                                        {'entities': [(0, 7, 'QUANTITY'), (46, 56, 'QUANTITY')]}),
                                       ('4 Confit Duck Legs at room temperature', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('3 tablespoons extra-virgin olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('2 medium onions, finely chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('2 large carrots, finely chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('2 celery ribs, finely chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('4 large garlic cloves, finely chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('2 Turkish bay leaves or 1 California',
                                        {'entities': [(0, 1, 'CARDINAL'), (24, 25, 'CARDINAL')]}),
                                       ('2 large thyme sprigs', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('2 whole cloves', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('5 cups reduced-sodium chicken broth', {'entities': [(0, 6, 'QUANTITY')]}),
                                       ('8 cups water', {'entities': [(0, 6, 'QUANTITY')]}),
                                       ('1 (15-ounce) can diced tomatoes, drained',
                                        {'entities': [(0, 16, 'QUANTITY')]}),
                                       ('1/3 cup Armagnac or Cognac', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1/2 cup chopped flat-leaf parsley', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1 cup fresh bread crumbs (about 2 slices)',
                                        {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('2 tablespoons olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('2 tablespoons drained bottled horseradish, or to taste',
                                        {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('a 1-pound piece boneless pork loin', {'entities': [(2, 9, 'QUANTITY')]}),
                                       ('1 1/2 tablespoons Dijon mustard', {'entities': [(0, 17, 'QUANTITY')]}),
                                       ('Accompaniment if desired:', {'entities': []}),
                                       ('2 tablespoons vegetable oil', {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('3/4 pound red cabbage, sliced thin (about 6 cups)',
                                        {'entities': [(0, 9, 'QUANTITY')]}),
                                       ('1 medium red onion, sliced thin', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('1/4 cup water', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1/2 cup balsamic vinegar', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1 tablespoon sugar', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('2 cups all-purpose flour', {'entities': [(0, 6, 'QUANTITY')]}),
                                       ('3/4 cup sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1 1/2 teaspoons baking powder', {'entities': [(0, 15, 'QUANTITY')]}),
                                       ('1/2 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1/2 stick (1/4 cup) cold unsalted butter, cut into small pieces',
                                        {'entities': [(11, 18, 'QUANTITY')]}),
                                       ('1 whole large egg, lightly beaten', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('1/3 cup whole milk', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1/2 teaspoon vanilla extract', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1/4 teaspoon almond extract', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1 cup whole almonds with skins (5 1/2 oz), toasted and cooled',
                                        {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('1 cup dried apricots (6 oz), quartered', {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('1 large egg yolk beaten with 1 tablespoon water for egg wash',
                                        {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('Special equipment: parchment paper', {'entities': []}),
                                       ('1-1/2 teaspoons extra-virgin olive oil or garlic oil',
                                        {'entities': [(0, 15, 'QUANTITY')]}),
                                       ('1 teaspoon minced garlic', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1/4 cup fine dried bread crumbs', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('Pinch gray salt', {'entities': []}),
                                       ('Freshly ground pepper', {'entities': []}),
                                       ('1 tablespoon finely chopped fresh parsley',
                                        {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1 teaspoon freshly grated lemon zest', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 tablespoon freshly grated Parmesan cheese',
                                        {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('Unsalted butter for baking dish', {'entities': []}),
                                       ('1 large bunch asparagus, about 1 pound, trimmed to even lengths and cooked '
                                        'for 4 minutes in boiling, salted water',
                                        {'entities': [(0, 1, 'CARDINAL'), (31, 38, 'QUANTITY')]}),
                                       ('2 tablespoons extra-virgin olive oil', {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('Gray salt and freshly ground pepper', {'entities': []}),
                                       ('8 thin slices prosciutto', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('4 pounds McIntosh apples, peeled, cored, cut into 1-inch chunks',
                                        {'entities': [(0, 8, 'QUANTITY')]}),
                                       ('1 1/2 cups apple cider', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1/2 cup (packed) golden brown sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1 tablespoon lemon juice', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('2 tablespoons minced crystallized ginger',
                                        {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('1 cup firmly packed dried figs (as soft as possible)',
                                        {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('1 cup firmly packed pitted dates', {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('1/3 cup water', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1/2 cup plus 2 tablespoons granulated refined sugar',
                                        {'entities': [(0, 7, 'QUANTITY'), (13, 26, 'QUANTITY')]}),
                                       ('1 3/4 cups all-purpose flour', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 tablespoon ground anise seeds', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1/4 teaspoon baking powder', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1/4 teaspoon baking soda', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1/4 teaspoon salt', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1 stick (1/2 cup) unsalted butter, softened',
                                        {'entities': [(0, 1, 'CARDINAL'), (9, 16, 'QUANTITY')]}),
                                       ('4 ounces cream cheese', {'entities': [(0, 8, 'QUANTITY')]}),
                                       ('1 teaspoon vanilla extract', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 large egg yolk', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('1/4 cup granulated raw sugar (turbinado or Demerara)',
                                        {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('4 pounds zucchini, peeled, quartered lengthwise, cored, and chopped',
                                        {'entities': [(0, 8, 'QUANTITY')]}),
                                       ('2 medium onions, chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('1 medium red bell pepper, chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('2 tablespoons salt', {'entities': [(0, 13, 'QUANTITY')]}),
                                       ('1 1/2 cups sugar', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 cup water', {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('1 cup distilled white vinegar', {'entities': [(0, 5, 'QUANTITY')]}),
                                       ('1 teaspoon celery seeds', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 teaspoon freshly grated nutmeg', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 teaspoon turmeric if desired', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1/2 teaspoon freshly ground black pepper, or to taste',
                                        {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1/2 cup kosher salt', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('1/2 cup sugar', {'entities': [(0, 7, 'QUANTITY')]}),
                                       ('12 black peppercorns', {'entities': [(0, 2, 'CARDINAL')]}),
                                       ('6 garlic coves, roughly chopped', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('6 fresh thyme sprigs', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('2 bay leaves', {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('1 small yellow onion, peeled and sliced into rings',
                                        {'entities': [(0, 1, 'CARDINAL')]}),
                                       ('4 cups ice cubes', {'entities': [(0, 6, 'QUANTITY')]}),
                                       ('One 3-pound boneless pork loin roast with a nice fat cap layer on top',
                                        {'entities': [(4, 11, 'QUANTITY')]}),
                                       ('1 large (about 4-ounce) Andouille sausage link',
                                        {'entities': [(0, 1, 'CARDINAL'), (15, 22, 'QUANTITY')]}),
                                       ('Kosher salt and freshly ground black pepper', {'entities': []}),
                                       ('1 tablespoon granulated garlic', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1 tablespoon paprika', {'entities': [(0, 12, 'QUANTITY')]}),
                                       ('1 teaspoon ground cumin', {'entities': [(0, 10, 'QUANTITY')]}),
                                       ('1 to 2 tablespoons canola oil', {'entities': [(5, 18, 'QUANTITY')]}),
                                       ("Creole mustard (e.g., Zatarain's)", {'entities': []}),
                                       ('Grill with lid, large freezer bag, honing steel, instant-read meat '
                                        'thermometer.',
                                        {'entities': []})]

annotated_for_testing_with_INGREDIENT = [('1 pound dried white beans such as cannellini (2 1/2 cups), picked over and '
                                          'rinsed',
                                          {'entities': [(8, 25, 'INGREDIENT'),
                                                        (34, 44, 'INGREDIENT'),
                                                        (0, 7, 'QUANTITY'),
                                                        (46, 56, 'QUANTITY')]}),
                                         ('4 Confit Duck Legs at room temperature',
                                          {'entities': [(2, 18, 'INGREDIENT')]}),
                                         ('3 tablespoons extra-virgin olive oil',
                                          {'entities': [(14, 36, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('2 medium onions, finely chopped', {'entities': [(9, 15, 'INGREDIENT')]}),
                                         ('2 large carrots, finely chopped', {'entities': [(8, 15, 'INGREDIENT')]}),
                                         ('2 celery ribs, finely chopped', {'entities': [(2, 13, 'INGREDIENT')]}),
                                         ('4 large garlic cloves, finely chopped',
                                          {'entities': [(8, 21, 'INGREDIENT')]}),
                                         ('2 Turkish bay leaves or 1 California',
                                          {'entities': [(2, 20, 'INGREDIENT'), (26, 36, 'INGREDIENT')]}),
                                         ('2 large thyme sprigs', {'entities': [(8, 20, 'INGREDIENT')]}),
                                         ('2 whole cloves', {'entities': [(2, 14, 'INGREDIENT')]}),
                                         ('5 cups reduced-sodium chicken broth',
                                          {'entities': [(7, 35, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                         ('8 cups water', {'entities': [(7, 12, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                         ('1 (15-ounce) can diced tomatoes, drained',
                                          {'entities': [(17, 31, 'INGREDIENT'), (0, 16, 'QUANTITY')]}),
                                         ('1/3 cup Armagnac or Cognac',
                                          {'entities': [(8, 16, 'INGREDIENT'),
                                                        (20, 26, 'INGREDIENT'),
                                                        (0, 7, 'QUANTITY')]}),
                                         ('1/2 cup chopped flat-leaf parsley',
                                          {'entities': [(16, 33, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1 cup fresh bread crumbs (about 2 slices)',
                                          {'entities': [(12, 24, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('2 tablespoons olive oil',
                                          {'entities': [(14, 23, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('2 tablespoons drained bottled horseradish, or to taste',
                                          {'entities': [(22, 41, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('a 1-pound piece boneless pork loin',
                                          {'entities': [(16, 34, 'INGREDIENT'), (2, 9, 'QUANTITY')]}),
                                         ('1 1/2 tablespoons Dijon mustard',
                                          {'entities': [(18, 31, 'INGREDIENT'), (0, 17, 'QUANTITY')]}),
                                         ('Accompaniment if desired:', {'entities': []}),
                                         ('2 tablespoons vegetable oil',
                                          {'entities': [(14, 27, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('3/4 pound red cabbage, sliced thin (about 6 cups)',
                                          {'entities': [(10, 21, 'INGREDIENT'), (0, 9, 'QUANTITY')]}),
                                         ('1 medium red onion, sliced thin', {'entities': [(9, 18, 'INGREDIENT')]}),
                                         ('1/4 cup water', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1/2 cup balsamic vinegar',
                                          {'entities': [(8, 24, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1 tablespoon sugar',
                                          {'entities': [(13, 18, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('2 cups all-purpose flour',
                                          {'entities': [(7, 24, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                         ('3/4 cup sugar', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1 1/2 teaspoons baking powder',
                                          {'entities': [(16, 29, 'INGREDIENT'), (0, 15, 'QUANTITY')]}),
                                         ('1/2 teaspoon salt',
                                          {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1/2 stick (1/4 cup) cold unsalted butter, cut into small pieces',
                                          {'entities': [(25, 40, 'INGREDIENT'), (11, 18, 'QUANTITY')]}),
                                         ('1 whole large egg, lightly beaten', {'entities': [(14, 17, 'INGREDIENT')]}),
                                         ('1/3 cup whole milk',
                                          {'entities': [(8, 18, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1/2 teaspoon vanilla extract',
                                          {'entities': [(13, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1/4 teaspoon almond extract',
                                          {'entities': [(13, 27, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1 cup whole almonds with skins (5 1/2 oz), toasted and cooled',
                                          {'entities': [(12, 19, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('1 cup dried apricots (6 oz), quartered',
                                          {'entities': [(6, 20, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('1 large egg yolk beaten with 1 tablespoon water for egg wash',
                                          {'entities': [(8, 16, 'INGREDIENT')]}),
                                         ('Special equipment: parchment paper', {'entities': [(19, 34, 'INGREDIENT')]}),
                                         ('1-1/2 teaspoons extra-virgin olive oil or garlic oil',
                                          {'entities': [(16, 38, 'INGREDIENT'),
                                                        (42, 52, 'INGREDIENT'),
                                                        (0, 15, 'QUANTITY')]}),
                                         ('1 teaspoon minced garlic',
                                          {'entities': [(18, 24, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1/4 cup fine dried bread crumbs',
                                          {'entities': [(19, 31, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('Pinch gray salt', {'entities': [(6, 15, 'INGREDIENT')]}),
                                         ('Freshly ground pepper', {'entities': [(8, 21, 'INGREDIENT')]}),
                                         ('1 tablespoon finely chopped fresh parsley',
                                          {'entities': [(28, 41, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1 teaspoon freshly grated lemon zest',
                                          {'entities': [(26, 36, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 tablespoon freshly grated Parmesan cheese',
                                          {'entities': [(28, 43, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('Unsalted butter for baking dish', {'entities': [(0, 15, 'INGREDIENT')]}),
                                         ('1 large bunch asparagus, about 1 pound, trimmed to even lengths and cooked '
                                          'for 4 minutes in boiling, salted water',
                                          {'entities': [(14, 23, 'INGREDIENT'), (31, 38, 'QUANTITY')]}),
                                         ('2 tablespoons extra-virgin olive oil',
                                          {'entities': [(14, 36, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('Gray salt and freshly ground pepper',
                                          {'entities': [(0, 9, 'INGREDIENT'), (22, 35, 'INGREDIENT')]}),
                                         ('8 thin slices prosciutto', {'entities': [(14, 24, 'INGREDIENT')]}),
                                         ('4 pounds McIntosh apples, peeled, cored, cut into 1-inch chunks',
                                          {'entities': [(9, 24, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                                         ('1 1/2 cups apple cider',
                                          {'entities': [(11, 22, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1/2 cup (packed) golden brown sugar',
                                          {'entities': [(17, 35, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1 tablespoon lemon juice',
                                          {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('2 tablespoons minced crystallized ginger',
                                          {'entities': [(21, 40, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('1 cup firmly packed dried figs (as soft as possible)',
                                          {'entities': [(20, 30, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('1 cup firmly packed pitted dates',
                                          {'entities': [(20, 32, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('1/3 cup water', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1/2 cup plus 2 tablespoons granulated refined sugar',
                                          {'entities': [(27, 51, 'INGREDIENT'),
                                                        (0, 7, 'QUANTITY'),
                                                        (13, 26, 'QUANTITY')]}),
                                         ('1 3/4 cups all-purpose flour',
                                          {'entities': [(11, 28, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 tablespoon ground anise seeds',
                                          {'entities': [(13, 31, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1/4 teaspoon baking powder',
                                          {'entities': [(13, 26, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1/4 teaspoon baking soda',
                                          {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1/4 teaspoon salt',
                                          {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1 stick (1/2 cup) unsalted butter, softened',
                                          {'entities': [(18, 33, 'INGREDIENT'), (9, 16, 'QUANTITY')]}),
                                         ('4 ounces cream cheese',
                                          {'entities': [(9, 21, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                                         ('1 teaspoon vanilla extract',
                                          {'entities': [(11, 26, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 large egg yolk', {'entities': [(8, 16, 'INGREDIENT')]}),
                                         ('1/4 cup granulated raw sugar (turbinado or Demerara)',
                                          {'entities': [(8, 28, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('4 pounds zucchini, peeled, quartered lengthwise, cored, and chopped',
                                          {'entities': [(9, 17, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                                         ('2 medium onions, chopped', {'entities': [(9, 15, 'INGREDIENT')]}),
                                         ('1 medium red bell pepper, chopped', {'entities': [(9, 24, 'INGREDIENT')]}),
                                         ('2 tablespoons salt',
                                          {'entities': [(14, 18, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                         ('1 1/2 cups sugar',
                                          {'entities': [(11, 16, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 cup water', {'entities': [(6, 11, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('1 cup distilled white vinegar',
                                          {'entities': [(16, 29, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                         ('1 teaspoon celery seeds',
                                          {'entities': [(11, 23, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 teaspoon freshly grated nutmeg',
                                          {'entities': [(19, 32, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 teaspoon turmeric if desired',
                                          {'entities': [(11, 19, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1/2 teaspoon freshly ground black pepper, or to taste',
                                          {'entities': [(21, 40, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1/2 cup kosher salt',
                                          {'entities': [(8, 19, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('1/2 cup sugar', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                         ('12 black peppercorns', {'entities': [(3, 20, 'INGREDIENT')]}),
                                         ('6 garlic coves, roughly chopped', {'entities': [(2, 8, 'INGREDIENT')]}),
                                         ('6 fresh thyme sprigs', {'entities': [(8, 13, 'INGREDIENT')]}),
                                         ('2 bay leaves', {'entities': [(2, 12, 'INGREDIENT')]}),
                                         ('1 small yellow onion, peeled and sliced into rings',
                                          {'entities': [(8, 20, 'INGREDIENT')]}),
                                         ('4 cups ice cubes',
                                          {'entities': [(7, 16, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                         ('One 3-pound boneless pork loin roast with a nice fat cap layer on top',
                                          {'entities': [(12, 36, 'INGREDIENT'), (4, 11, 'QUANTITY')]}),
                                         ('1 large (about 4-ounce) Andouille sausage link',
                                          {'entities': [(24, 46, 'INGREDIENT'), (15, 22, 'QUANTITY')]}),
                                         ('Kosher salt and freshly ground black pepper',
                                          {'entities': [(24, 43, 'INGREDIENT')]}),
                                         ('1 tablespoon granulated garlic',
                                          {'entities': [(13, 30, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1 tablespoon paprika',
                                          {'entities': [(13, 20, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                         ('1 teaspoon ground cumin',
                                          {'entities': [(18, 23, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                         ('1 to 2 tablespoons canola oil',
                                          {'entities': [(19, 29, 'INGREDIENT'), (5, 18, 'QUANTITY')]}),
                                         ("Creole mustard (e.g., Zatarain's)", {'entities': [(0, 14, 'INGREDIENT')]}),
                                         ('Grill with lid, large freezer bag, honing steel, instant-read meat '
                                          'thermometer.',
                                          {'entities': []})]

annotated_for_testing_with_all = [('1 pound dried white beans such as cannellini (2 1/2 cups), picked over and '
                                   'rinsed',
                                   {'entities': [(8, 25, 'INGREDIENT'),
                                                 (34, 44, 'INGREDIENT'),
                                                 (0, 7, 'QUANTITY'),
                                                 (46, 56, 'QUANTITY')]}),
                                  ('4 Confit Duck Legs at room temperature',
                                   {'entities': [(0, 1, 'CARDINAL'), (2, 18, 'INGREDIENT')]}),
                                  ('3 tablespoons extra-virgin olive oil',
                                   {'entities': [(14, 36, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('2 medium onions, finely chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (9, 15, 'INGREDIENT')]}),
                                  ('2 large carrots, finely chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 15, 'INGREDIENT')]}),
                                  ('2 celery ribs, finely chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (2, 13, 'INGREDIENT')]}),
                                  ('4 large garlic cloves, finely chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 21, 'INGREDIENT')]}),
                                  ('2 Turkish bay leaves or 1 California',
                                   {'entities': [(0, 1, 'CARDINAL'),
                                                 (24, 25, 'CARDINAL'),
                                                 (2, 20, 'INGREDIENT'),
                                                 (26, 36, 'INGREDIENT')]}),
                                  ('2 large thyme sprigs',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 20, 'INGREDIENT')]}),
                                  ('2 whole cloves', {'entities': [(0, 1, 'CARDINAL'), (2, 14, 'INGREDIENT')]}),
                                  ('5 cups reduced-sodium chicken broth',
                                   {'entities': [(7, 35, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                  ('8 cups water', {'entities': [(7, 12, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                  ('1 (15-ounce) can diced tomatoes, drained',
                                   {'entities': [(17, 31, 'INGREDIENT'), (0, 16, 'QUANTITY')]}),
                                  ('1/3 cup Armagnac or Cognac',
                                   {'entities': [(8, 16, 'INGREDIENT'),
                                                 (20, 26, 'INGREDIENT'),
                                                 (0, 7, 'QUANTITY')]}),
                                  ('1/2 cup chopped flat-leaf parsley',
                                   {'entities': [(16, 33, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1 cup fresh bread crumbs (about 2 slices)',
                                   {'entities': [(12, 24, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('2 tablespoons olive oil',
                                   {'entities': [(14, 23, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('2 tablespoons drained bottled horseradish, or to taste',
                                   {'entities': [(22, 41, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('a 1-pound piece boneless pork loin',
                                   {'entities': [(16, 34, 'INGREDIENT'), (2, 9, 'QUANTITY')]}),
                                  ('1 1/2 tablespoons Dijon mustard',
                                   {'entities': [(18, 31, 'INGREDIENT'), (0, 17, 'QUANTITY')]}),
                                  ('Accompaniment if desired:', {'entities': []}),
                                  ('2 tablespoons vegetable oil',
                                   {'entities': [(14, 27, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('3/4 pound red cabbage, sliced thin (about 6 cups)',
                                   {'entities': [(10, 21, 'INGREDIENT'), (0, 9, 'QUANTITY')]}),
                                  ('1 medium red onion, sliced thin',
                                   {'entities': [(0, 1, 'CARDINAL'), (9, 18, 'INGREDIENT')]}),
                                  ('1/4 cup water', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1/2 cup balsamic vinegar',
                                   {'entities': [(8, 24, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1 tablespoon sugar',
                                   {'entities': [(13, 18, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('2 cups all-purpose flour',
                                   {'entities': [(7, 24, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                  ('3/4 cup sugar', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1 1/2 teaspoons baking powder',
                                   {'entities': [(16, 29, 'INGREDIENT'), (0, 15, 'QUANTITY')]}),
                                  ('1/2 teaspoon salt',
                                   {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1/2 stick (1/4 cup) cold unsalted butter, cut into small pieces',
                                   {'entities': [(25, 40, 'INGREDIENT'), (11, 18, 'QUANTITY')]}),
                                  ('1 whole large egg, lightly beaten',
                                   {'entities': [(0, 1, 'CARDINAL'), (14, 17, 'INGREDIENT')]}),
                                  ('1/3 cup whole milk',
                                   {'entities': [(8, 18, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1/2 teaspoon vanilla extract',
                                   {'entities': [(13, 28, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1/4 teaspoon almond extract',
                                   {'entities': [(13, 27, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1 cup whole almonds with skins (5 1/2 oz), toasted and cooled',
                                   {'entities': [(12, 19, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('1 cup dried apricots (6 oz), quartered',
                                   {'entities': [(6, 20, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('1 large egg yolk beaten with 1 tablespoon water for egg wash',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 16, 'INGREDIENT')]}),
                                  ('Special equipment: parchment paper', {'entities': [(19, 34, 'INGREDIENT')]}),
                                  ('1-1/2 teaspoons extra-virgin olive oil or garlic oil',
                                   {'entities': [(16, 38, 'INGREDIENT'),
                                                 (42, 52, 'INGREDIENT'),
                                                 (0, 15, 'QUANTITY')]}),
                                  ('1 teaspoon minced garlic',
                                   {'entities': [(18, 24, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1/4 cup fine dried bread crumbs',
                                   {'entities': [(19, 31, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('Pinch gray salt', {'entities': [(6, 15, 'INGREDIENT')]}),
                                  ('Freshly ground pepper', {'entities': [(8, 21, 'INGREDIENT')]}),
                                  ('1 tablespoon finely chopped fresh parsley',
                                   {'entities': [(28, 41, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1 teaspoon freshly grated lemon zest',
                                   {'entities': [(26, 36, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 tablespoon freshly grated Parmesan cheese',
                                   {'entities': [(28, 43, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('Unsalted butter for baking dish', {'entities': [(0, 15, 'INGREDIENT')]}),
                                  ('1 large bunch asparagus, about 1 pound, trimmed to even lengths and cooked '
                                   'for 4 minutes in boiling, salted water',
                                   {'entities': [(0, 1, 'CARDINAL'),
                                                 (14, 23, 'INGREDIENT'),
                                                 (31, 38, 'QUANTITY')]}),
                                  ('2 tablespoons extra-virgin olive oil',
                                   {'entities': [(14, 36, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('Gray salt and freshly ground pepper',
                                   {'entities': [(0, 9, 'INGREDIENT'), (22, 35, 'INGREDIENT')]}),
                                  ('8 thin slices prosciutto',
                                   {'entities': [(0, 1, 'CARDINAL'), (14, 24, 'INGREDIENT')]}),
                                  ('4 pounds McIntosh apples, peeled, cored, cut into 1-inch chunks',
                                   {'entities': [(9, 24, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                                  ('1 1/2 cups apple cider',
                                   {'entities': [(11, 22, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1/2 cup (packed) golden brown sugar',
                                   {'entities': [(17, 35, 'INGREvbg1    `DIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1 tablespoon lemon juice',
                                   {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('2 tablespoons minced crystallized ginger',
                                   {'entities': [(21, 40, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('1 cup firmly packed dried figs (as soft as possible)',
                                   {'entities': [(20, 30, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('1 cup firmly packed pitted dates',
                                   {'entities': [(20, 32, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('1/3 cup water', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1/2 cup plus 2 tablespoons granulated refined sugar',
                                   {'entities': [(27, 51, 'INGREDIENT'),
                                                 (0, 7, 'QUANTITY'),
                                                 (13, 26, 'QUANTITY')]}),
                                  ('1 3/4 cups all-purpose flour',
                                   {'entities': [(11, 28, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 tablespoon ground anise seeds',
                                   {'entities': [(13, 31, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1/4 teaspoon baking powder',
                                   {'entities': [(13, 26, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1/4 teaspoon baking soda',
                                   {'entities': [(13, 24, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1/4 teaspoon salt',
                                   {'entities': [(13, 17, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1 stick (1/2 cup) unsalted butter, softened',
                                   {'entities': [(18, 33, 'INGREDIENT'), (9, 16, 'QUANTITY')]}),
                                  ('4 ounces cream cheese',
                                   {'entities': [(9, 21, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                                  ('1 teaspoon vanilla extract',
                                   {'entities': [(11, 26, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 large egg yolk',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 16, 'INGREDIENT')]}),
                                  ('1/4 cup granulated raw sugar (turbinado or Demerara)',
                                   {'entities': [(8, 28, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('4 pounds zucchini, peeled, quartered lengthwise, cored, and chopped',
                                   {'entities': [(9, 17, 'INGREDIENT'), (0, 8, 'QUANTITY')]}),
                                  ('2 medium onions, chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (9, 15, 'INGREDIENT')]}),
                                  ('1 medium red bell pepper, chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (9, 24, 'INGREDIENT')]}),
                                  ('2 tablespoons salt',
                                   {'entities': [(14, 18, 'INGREDIENT'), (0, 13, 'QUANTITY')]}),
                                  ('1 1/2 cups sugar',
                                   {'entities': [(11, 16, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 cup water', {'entities': [(6, 11, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('1 cup distilled white vinegar',
                                   {'entities': [(16, 29, 'INGREDIENT'), (0, 5, 'QUANTITY')]}),
                                  ('1 teaspoon celery seeds',
                                   {'entities': [(11, 23, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 teaspoon freshly grated nutmeg',
                                   {'entities': [(19, 32, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 teaspoon turmeric if desired',
                                   {'entities': [(11, 19, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1/2 teaspoon freshly ground black pepper, or to taste',
                                   {'entities': [(21, 40, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1/2 cup kosher salt',
                                   {'entities': [(8, 19, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('1/2 cup sugar', {'entities': [(8, 13, 'INGREDIENT'), (0, 7, 'QUANTITY')]}),
                                  ('12 black peppercorns',
                                   {'entities': [(0, 2, 'CARDINAL'), (3, 20, 'INGREDIENT')]}),
                                  ('6 garlic coves, roughly chopped',
                                   {'entities': [(0, 1, 'CARDINAL'), (2, 8, 'INGREDIENT')]}),
                                  ('6 fresh thyme sprigs',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 13, 'INGREDIENT')]}),
                                  ('2 bay leaves', {'entities': [(0, 1, 'CARDINAL'), (2, 12, 'INGREDIENT')]}),
                                  ('1 small yellow onion, peeled and sliced into rings',
                                   {'entities': [(0, 1, 'CARDINAL'), (8, 20, 'INGREDIENT')]}),
                                  ('4 cups ice cubes',
                                   {'entities': [(7, 16, 'INGREDIENT'), (0, 6, 'QUANTITY')]}),
                                  ('One 3-pound boneless pork loin roast with a nice fat cap layer on top',
                                   {'entities': [(12, 36, 'INGREDIENT'), (4, 11, 'QUANTITY')]}),
                                  ('1 large (about 4-ounce) Andouille sausage link',
                                   {'entities': [(0, 1, 'CARDINAL'),
                                                 (24, 46, 'INGREDIENT'),
                                                 (15, 22, 'QUANTITY')]}),
                                  ('Kosher salt and freshly ground black pepper',
                                   {'entities': [(24, 43, 'INGREDIENT')]}),
                                  ('1 tablespoon granulated garlic',
                                   {'entities': [(13, 30, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1 tablespoon paprika',
                                   {'entities': [(13, 20, 'INGREDIENT'), (0, 12, 'QUANTITY')]}),
                                  ('1 teaspoon ground cumin',
                                   {'entities': [(18, 23, 'INGREDIENT'), (0, 10, 'QUANTITY')]}),
                                  ('1 to 2 tablespoons canola oil',
                                   {'entities': [(19, 29, 'INGREDIENT'), (5, 18, 'QUANTITY')]}),
                                  ("Creole mustard (e.g., Zatarain's)", {'entities': [(0, 14, 'INGREDIENT')]}),
                                  ('Grill with lid, large freezer bag, honing steel, instant-read meat '
                                   'thermometer.',
                                   {'entities': []})]
